### ISSUE TITLE
Pipeline terminated prematurely with Exception thrown in fastq_polyA_stripper.py

### ISSUE THREAD

**Issue by lewynli** [nf-core/viralintegration#44]
### Description of the bug

When running the test profile in docker, the pipeline terminated prematurely with errors during the polyA stripping step.

Thanks so much for making the pipeline public!

### Command used and terminal output

```console
$ nextflow run nf-core/viralintegration -r dev -profile test,docker --outdir viralintegration/

.
.
.
[22/205cef] process > NFCORE_VIRALINTEGRATION:VIRALINTEGRATION:POLYA_STRIPPER (novirus_T1)                                [100%] 3 of 3, failed: 3 ✘
.
.
.
-[nf-core/viralintegration] Pipeline completed with errors-
Error executing process > 'NFCORE_VIRALINTEGRATION:VIRALINTEGRATION:POLYA_STRIPPER (redherring_T1)'

Caused by:
  Process `NFCORE_VIRALINTEGRATION:VIRALINTEGRATION:POLYA_STRIPPER (redherring_T1)` terminated with an error exit status (1)

Command executed:

  fastq_polyA_stripper.py \
      --out_prefix redherring_T1 \
      --left_fq redherring_T1.paired.trim_1.fastq.gz \
      --right_fq redherring_T1.paired.trim_2.fastq.gz
  
  pigz *.polyA-trimmed.fastq
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_VIRALINTEGRATION:VIRALINTEGRATION:POLYA_STRIPPER":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  8aed1c8e7e20: Download complete
  2a370c089507: Verifying Checksum
  2a370c089507: Download complete
  bfa6dab068ad: Download complete
  ab0228a8536e: Verifying Checksum
  ab0228a8536e: Download complete
  b39058095502: Verifying Checksum
  b39058095502: Download complete
  45571d207966: Download complete
  a66900e64b93: Verifying Checksum
  a66900e64b93: Download complete
  6c9397161bf6: Verifying Checksum
  6c9397161bf6: Download complete
  5739d5d87343: Verifying Checksum
  5739d5d87343: Download complete
  c877b56d3a11: Download complete
  6c9397161bf6: Pull complete
  bf1673cb8408: Pull complete
  8e78c49e9f5e: Pull complete
  346b6c8930e4: Pull complete
  8aed1c8e7e20: Pull complete
  9089a714f8ca: Verifying Checksum
  9089a714f8ca: Download complete
  bfa6dab068ad: Pull complete
  2a370c089507: Pull complete
  ab0228a8536e: Pull complete
  b39058095502: Pull complete
  45571d207966: Pull complete
  c60043babdeb: Verifying Checksum
  c60043babdeb: Download complete
  a66900e64b93: Pull complete
  9089a714f8ca: Pull complete
  c60043babdeb: Pull complete
  5739d5d87343: Pull complete
  c877b56d3a11: Pull complete
  Digest: sha256:3756c245c57ca386676303cffdc888197cb5480c37256277ee63063f6f5b93ef
  Status: Downloaded newer image for trinityctat/ctat_vif:latest
  Traceback (most recent call last):
    File "/home/ubuntu/.nextflow/assets/nf-core/viralintegration/bin/fastq_polyA_stripper.py", line 203, in fastq_iterator
      readname = next(fh).rstrip()
  StopIteration
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/home/ubuntu/.nextflow/assets/nf-core/viralintegration/bin/fastq_polyA_stripper.py", line 248, in <module>
      main()
    File "/home/ubuntu/.nextflow/assets/nf-core/viralintegration/bin/fastq_polyA_stripper.py", line 63, in main
      for left_read_tuple in left_fq_iterator:
  RuntimeError: generator raised StopIteration
```

### System information

Nextflow version: 22.10.4
Hardware: AWS
Container engine: Docker
OS: Ubuntu
Version of nf-core/viralintegration: v1.0dev-ga6285ad

**Comment by lewynli** [comment]
@Emiller88 can this be the problem?

The fastq_iterator is iterating "too much" and is not exiting properly.  The while loop is trying to execute the statement

```
readname = next(fh).rstrip()

```

even at the end of a fastq file, where there are no fastq records left.  Putting "if not readname" at the end of the while loop is not preventing the loop from trying to execute the statement improperly.

I modified the iterator by wrapping the content of the whole loop in a try-except, and it seemed to have solved the problem on my AWS EC2 at least.  See my modified iterator below.

Just a question: why not used Biopython SeqIO to parse fastq?

Hope this helps.  Thanks so much!

```
def fastq_iterator(fastq_filename):

    if re.search(".gz$", fastq_filename):
        fh = gzip.open(fastq_filename, "rt", encoding="utf-8")
    else:
        fh = open(fastq_filename, "rt", encoding="utf-8")

    have_records = True
    while have_records:
        try:
            readname = next(fh).rstrip()
            readseq = next(fh).rstrip()
            L3 = next(fh).rstrip()
            quals = next(fh).rstrip()

            yield (readname, readseq, L3, quals)
        except:
            break
        
    return
```

**Comment by edmundmiller** [comment]
Awesome! We can definitely make that change! Feel free to PR it yourself if you'd like!

> why not used Biopython SeqIO to parse fastq?

I think that's a question @brianjohnhaas may be able to answer. I'll see if the ctat script has been updated since then, and if not we'll start to deviate.
